import { Quest, GameItem, CampusEventItem } from './quest';

export const INITIAL_ITEMS: GameItem[] = [
  {
    id: 'item-compass',
    name: 'เข็มทิศดวงดาวนักสำรวจ',
    description: 'เข็มทิศโบราณที่สั่นไหวเมื่อเข้าใกล้สิ่งลี้ลับรอบมหาวิทยาลัย',
    icon: 'compass',
    type: 'artifact',
    rarity: 'RARE',
    acquiredAt: new Date().toISOString(),
  },
  {
    id: 'item-kku-badge',
    name: 'เหรียญตราต้นกาลพฤกษ์',
    description: 'สัญลักษณ์แห่งความกล้าหาญและความรู้ของชาวขอนแก่น',
    icon: 'shield-checkmark',
    type: 'badge',
    rarity: 'COMMON',
    acquiredAt: new Date().toISOString(),
  },
];

export const INITIAL_EVENTS: CampusEventItem[] = [
  {
    id: 'evt-1',
    title: 'KKU Tech Expo & Hackathon 2026',
    category: 'Technology & Academic',
    startsAt: new Date(Date.now() + 45 * 60 * 1000).toISOString(),
    endsAt: new Date(Date.now() + 5 * 60 * 60 * 1000).toISOString(),
    timeRangeText: '09:00 - 16:30 น.',
    location: {
      name: 'อุทยานวิทยาศาสตร์ ภาคตะวันออกเฉียงเหนือ มข.',
      latitude: 16.4730,
      longitude: 102.8206,
    },
    description: 'งานแสดงผลงานนวัตกรรมและเทคโนโลยีของนักศึกษาวิทยาการคอมพิวเตอร์และการแข่งขันพัฒนาโมบายแอปพลิเคชัน',
    rewardXp: 300,
    rewardCoins: 150,
    // ภาพ Hackathon / Tech Exhibition นวัตกรรมจริง
    imageUrl: 'https://images.unsplash.com/photo-1504384308090-c894fdcc538d?auto=format&fit=crop&w=800&q=80',
  },
  {
    id: 'evt-2',
    title: 'ดนตรีริมบึงสีฐาน (Si Than Music Fest)',
    category: 'Cultural & Art',
    startsAt: new Date(Date.now() + 2 * 60 * 60 * 1000).toISOString(),
    endsAt: new Date(Date.now() + 6 * 60 * 60 * 1000).toISOString(),
    timeRangeText: '17:00 - 21:00 น.',
    location: {
      name: 'ริมบึงสีฐาน มหาวิทยาลัยขอนแก่น',
      latitude: 16.4564,
      longitude: 102.8079,
    },
    description: 'กิจกรรมการแสดงดนตรีสดและพื้นที่แสดงความคิดสร้างสรรค์ริมบึงสีฐานยามเย็น',
    rewardXp: 200,
    rewardCoins: 100,
    // ภาพเวทีคอนเสิร์ตดนตรีริมน้ำ แสงสีเสียงสดใส
    imageUrl: 'https://images.unsplash.com/photo-1514525253161-7a46d19cd819?auto=format&fit=crop&w=800&q=80',
  },
  {
    id: 'evt-3',
    title: 'บรรยายพิเศษ: Future AI & Autonomous Agents',
    category: 'Lecture & Seminar',
    startsAt: new Date(Date.now() + 24 * 60 * 60 * 1000).toISOString(),
    endsAt: new Date(Date.now() + 27 * 60 * 60 * 1000).toISOString(),
    timeRangeText: '13:00 - 16:00 น.',
    location: {
      name: 'วิทยาลัยการคอมพิวเตอร์ (CP KKU)',
      latitude: 16.4745,
      longitude: 102.8240,
    },
    description: 'เรียนรู้เทคโนโลยี AI ยุคใหม่ การพัฒนา Agentic Coding และโอกาสทางสายงานในอนาคต',
    rewardXp: 250,
    rewardCoins: 120,
    // ภาพห้องสัมมนาบรรยาย AI & Tech Talk
    imageUrl: 'https://images.unsplash.com/photo-1531482615713-2afd69097998?auto=format&fit=crop&w=800&q=80',
  },
];

export const INITIAL_QUESTS: Quest[] = [
  // --- เควสต์ที่ผูกกับกิจกรรมเริ่มต้น (Event-linked quests) ---
  {
    id: 'q-evt-1',
    title: '[กิจกรรม] KKU Tech Expo & Hackathon 2026',
    description: 'ร่วมกิจกรรม: งานแสดงผลงานนวัตกรรมและเทคโนโลยีของนักศึกษา เดินทางไปยังอุทยานวิทยาศาสตร์และถ่ายภาพหลักฐานการร่วมงาน',
    category: 'event',
    difficulty: 'MEDIUM',
    rewardXp: 300,
    rewardCoins: 150,
    location: {
      name: 'อุทยานวิทยาศาสตร์ ภาคตะวันออกเฉียงเหนือ มข.',
      latitude: 16.4730,
      longitude: 102.8206,
    },
    targetRadiusMeters: 80,
    hintText: 'เช็กอิน ณ อุทยานวิทยาศาสตร์ มข. เวลา 09:00 - 16:30 น.',
    requiredProofPhoto: true,
    status: 'available',
    eventId: 'evt-1',
    imageUrl: 'https://images.unsplash.com/photo-1504384308090-c894fdcc538d?auto=format&fit=crop&w=800&q=80',
  },
  {
    id: 'q-evt-2',
    title: '[กิจกรรม] ดนตรีริมบึงสีฐาน (Si Than Music Fest)',
    description: 'ร่วมกิจกรรม: สัมผัสบรรยากาศดนตรีสดและพื้นที่แสดงความคิดสร้างสรรค์ริมบึงสีฐานยามเย็น',
    category: 'event',
    difficulty: 'EASY',
    rewardXp: 200,
    rewardCoins: 100,
    location: {
      name: 'ริมบึงสีฐาน มหาวิทยาลัยขอนแก่น',
      latitude: 16.4564,
      longitude: 102.8079,
    },
    targetRadiusMeters: 100,
    hintText: 'เช็กอิน ณ ลานริมบึงสีฐาน เวลา 17:00 - 21:00 น.',
    requiredProofPhoto: true,
    status: 'available',
    eventId: 'evt-2',
    imageUrl: 'https://images.unsplash.com/photo-1514525253161-7a46d19cd819?auto=format&fit=crop&w=800&q=80',
  },
  {
    id: 'q-evt-3',
    title: '[กิจกรรม] บรรยายพิเศษ: Future AI & Autonomous Agents',
    description: 'ร่วมฟังการบรรยายพิเศษด้าน AI ยุคใหม่ ณ วิทยาลัยการคอมพิวเตอร์ มข. และบันทึกภาพหลักฐานการเข้าร่วม',
    category: 'event',
    difficulty: 'MEDIUM',
    rewardXp: 250,
    rewardCoins: 120,
    location: {
      name: 'วิทยาลัยการคอมพิวเตอร์ (CP KKU)',
      latitude: 16.4745,
      longitude: 102.8240,
    },
    targetRadiusMeters: 60,
    hintText: 'เช็กอิน ณ วิทยาลัยการคอมพิวเตอร์ มข. เวลา 13:00 - 16:00 น.',
    requiredProofPhoto: true,
    status: 'available',
    eventId: 'evt-3',
    imageUrl: 'https://images.unsplash.com/photo-1531482615713-2afd69097998?auto=format&fit=crop&w=800&q=80',
  },
  // --- เควสต์สำรวจสถานที่ทั่วไป (Exploration quests) ---

  {
    id: 'q-kku-gate',
    title: 'ผู้มาเยือนดินแดนมอดินแดง',
    description: 'เดินทางไปยังประตูทางเข้าหลักมหาวิทยาลัยขอนแก่น และเก็บภาพถ่ายบันทึกการเริ่มต้นการผจญภัย',
    category: 'exploration',
    difficulty: 'EASY',
    rewardXp: 120,
    rewardCoins: 50,
    rewardItem: {
      id: 'item-mordindaeng-stone',
      name: 'ศิลาฝุ่นดินแดง',
      description: 'ดินลูกรังมอดินแดงอันเป็นตำนาน เพิ่มพลังกายในการเดินสำรวจ',
      icon: 'sparkles',
      type: 'relic',
      rarity: 'COMMON',
    },
    location: {
      name: 'ซุ้มประตูกาลพฤกษ์ มข.',
      latitude: 16.4730,
      longitude: 102.8206,
    },
    targetRadiusMeters: 60,
    hintText: 'มองหาซุ้มประตูใหญ่สีขาวตัดดินสีส้มอิฐ',
    requiredProofPhoto: true,
    status: 'available',
    imageUrl: 'https://images.unsplash.com/photo-1541829070764-84a7d30dd3f3?auto=format&fit=crop&w=800&q=80',
  },
  {
    id: 'q-sc-complex',
    title: 'ห้องแล็บแห่งวิทยาการคอมพิวเตอร์',
    description: 'สำรวจศูนย์กลางแห่งโค้ดและปัญญาประดิษฐ์ ณ วิทยาลัยการคอมพิวเตอร์ (CP KKU)',
    category: 'landmark',
    difficulty: 'MEDIUM',
    rewardXp: 250,
    rewardCoins: 120,
    rewardItem: {
      id: 'item-ai-core',
      name: 'ผลึกแกนประมวลผลควอนตัม',
      description: 'ชิปจำลองการคิดของ AI ผู้ช่วยสำรวจโลก',
      icon: 'hardware-chip',
      type: 'artifact',
      rarity: 'EPIC',
    },
    location: {
      name: 'วิทยาลัยการคอมพิวเตอร์ มหาวิทยาลัยขอนแก่น',
      latitude: 16.4745,
      longitude: 102.8240,
    },
    targetRadiusMeters: 50,
    hintText: 'อาคารตึกกระจกทันสมัย ใกล้ตึกฟิสิกส์',
    requiredProofPhoto: true,
    status: 'available',
    imageUrl: 'https://images.unsplash.com/photo-1526374965328-7f61d4dc18c5?auto=format&fit=crop&w=800&q=80',
  },
  {
    id: 'q-sithan-lake',
    title: 'สายลมแห่งบึงสีฐาน',
    description: 'เดินทางสู่อัญมณีริมน้ำฝั่งตะวันตกเพื่อสัมผัสพลังงานธรรมชาติยามเย็น',
    category: 'exploration',
    difficulty: 'EASY',
    rewardXp: 180,
    rewardCoins: 80,
    location: {
      name: 'ริมบึงสีฐาน และหอศิลปวัฒนธรรม',
      latitude: 16.4564,
      longitude: 102.8079,
    },
    targetRadiusMeters: 80,
    hintText: 'ลานริมน้ำที่มีผู้คนวิ่งออกกำลังกายและพญานาคพ่นน้ำ',
    requiredProofPhoto: false,
    status: 'available',
    imageUrl: 'https://images.unsplash.com/photo-1507525428034-b723cf961d3e?auto=format&fit=crop&w=800&q=80',
  },
  {
    id: 'q-central-mall',
    title: 'ชุมทางการค้าแห่งมหานคร',
    description: 'ภารกิจสำรวจจุดนัดพบขนาดใหญ่ใจกลางเมืองขอนแก่นเพื่อเสบียงเดินทาง',
    category: 'landmark',
    difficulty: 'MEDIUM',
    rewardXp: 200,
    rewardCoins: 150,
    location: {
      name: 'เซ็นทรัล ขอนแก่น (Central Khon Kaen)',
      latitude: 16.4324,
      longitude: 102.8265,
    },
    targetRadiusMeters: 70,
    hintText: 'ประตูหน้าทางเข้าติดถนนมิตรภาพ',
    requiredProofPhoto: true,
    status: 'available',
    imageUrl: 'https://images.unsplash.com/photo-1519501025264-65ba15a82390?auto=format&fit=crop&w=800&q=80',
  },
  {
    id: 'q-nong-wang',
    title: 'พระมหาธาตุเก้าชั้นวัดหนองแวง',
    description: 'เควสต์ระดับตำนาน บันทึกภาพพระมหาธาตุแก่นนครราชอนุสรณ์เจดีย์ 9 ชั้นริมบึงแก่นนคร',
    category: 'secret',
    difficulty: 'HARD',
    rewardXp: 500,
    rewardCoins: 300,
    rewardItem: {
      id: 'item-holy-relic',
      name: 'พระเครื่องคุ้มภัยนักเดินทาง',
      description: 'เพิ่มเกราะป้องกันและโชคลาภในการค้นหาเควสต์ลับ',
      icon: 'diamond',
      type: 'relic',
      rarity: 'LEGENDARY',
    },
    location: {
      name: 'วัดหนองแวง พระอารามหลวง',
      latitude: 16.4158,
      longitude: 102.8388,
    },
    targetRadiusMeters: 60,
    hintText: 'ยอดเจดีย์สีทองอร่าม 9 ชั้นที่มองเห็นได้แต่ไกล',
    requiredProofPhoto: true,
    status: 'available',
    imageUrl: 'https://images.unsplash.com/photo-1528181304800-259b08848526?auto=format&fit=crop&w=800&q=80',
  },
];
